version: "3.9"
services:
  playlist-service:
    networks:
      - inter_server_connection
  queue-service:
    networks:
      - inter_server_connection

networks:
  inter_server_connection:
    external: true