version: '3.9'
services:
  playlist-postgres:
    container_name: playlist-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=playlistdb
    ports:
      - "5433:5432"
    networks:
      - playlist-microservice_network
    env_file:
      - .env
  playlist-microservice:
    container_name: playlist-microservice
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
    depends_on:
      - playlist-postgres
    links:
      - playlist-postgres
    networks:
      - playlist-microservice_network
      - musicshop_backend_network
    env_file:
      - .env

networks:
  playlist-microservice_network:
    external: true
  musicshop_backend_network:
    external: true