apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-app
  labels:
    app: playlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist
  template:
    metadata:
      name: hello-world-pod
      labels:
        app: playlist
    spec:
      containers:
        - name: hello-world
          image: team-f-playlist-microservice-jvm
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: playlist-service-secret
                  key: postgres_username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playlist-service-secret
                  key: postgres_password
                  optional: false
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: playlist-rest
