apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: playlist-service-secret
                  key: postgres_username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playlist-service-secret
                  key: postgres_password
                  optional: false
            - name: POSTGRES_DB
              value: playlistdb
          ports:
            - containerPort: 5432
              name: postgresql
#              TODO persistent volume
#          volumeMounts:
#            - name: postgresql-persistent-storage
#              mountPath: /var/lib/postgresql/data
#      volumes:
#        - name: postgresql-persistent-storage
#          persistentVolumeClaim:
#            claimName: postgresql-pv-claim
