apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-app
  labels:
    app: playlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist
  template:
    metadata:
      name: hello-world-pod
      labels:
        app: playlist
    spec:
      containers:
        - name: hello-world
          image: team-f-playlist-microservice-jvm
          imagePullPolicy: Never #needed because we are using local docker-image not pulling from some registry
          ports:
            - containerPort: 8081
              name: playlist-rest